---
- name: creating control group
  hosts: localhost
  connection: local
  remote_user: root
  become: true
  tasks:
    - name : create ansible profile
      # -raw:  cgcreate -a root:root -t root:root -g cpuacct,memory,pids:ansible-runner
      command:  cgcreate -a root:root -t root:root -g cpuacct,memory,pids:ansible-runner
      #delegate_to: localhost
